[project]
name = "stacks-faucet"
description = "A Stacks Faucet project"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.faucet]
path = "contracts/faucet.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]
